---
title: "Presentation to MD/PhD Students"
subtitle: "Research Program in Psychiatry"
author:
  - name: Joey W. Trampush, Ph.D.
    orcid: 0000-0003-0830-508X
    email: Assistant Professor of Psychiatry and the Behavioral Sciences
    affiliations: 
      - Department of Psychiatry and the Behavioral Sciences
      - USC Keck School of Medicine
date: last-modified
date-format: long
location: USC Keck School of Medicine
format:
  # pptx:
  #   incremental: true
  clean-revealjs:
    transition: "none"
    logo: logo_ksom.jpg #logo_usc_ksom_black.jpg
    footer: <https://brainworkup./github.io/md-phd-students/>
    preview-links: auto
    standalone: true
    embed-resources: true
    width: 1600
    height: 900
    incremental: false
    slide-number: true
    show-slide-number: speaker
    fig-cap-location: top
    fig-format: svg
    pdf-separate-fragments: false
    fig-align: center
    overview: true
    menu: true    
    progress: true
    # chalkboard: 
    #   buttons: false
    css: styles.scss
execute:
    echo: false
    warning: false
    message: false
    cache: false
    freeze: auto
---

## Example slide

### This is a subtitle

Here we have some text that may run over several lines of the slide frame,
depending on how long it is.

- first item 
    - A sub item

Next, we'll brief review some theme-specific components.

- Note that _all_ of the standard Reveal.js
[features](https://quarto.org/docs/presentations/revealjs/)
can be used with this theme, even if we don't highlight them here.

## Additional theme classes

### Some extra things you can do with the clean theme

Special classes for emphasis

- `.alert` class for default emphasis, e.g. [important note]{.alert}.
- `.fg` class for custom colour, e.g. [important note]{.fg style="--col: #e64173"}.
- `.bg` class for custom background, e.g. [important note]{.bg style="--col: #e64173"}.

Cross-references

- `.button` class provides a Beamer-like button, e.g.
[[Summary]{.button}](#sec-summary)

## Want more?

### See our longer demo slides

We've deliberarely kept this template lean, to get you up and running as fast as
possible.

We provide a separate
[demo template](https://github.com/grantmcdermott/quarto-revealjs-clean-demo),
with more examples for integrating code, tables, figures, etc.

  - See the live demo slides
  [here](https://grantmcdermott.com/quarto-revealjs-clean-demo/template.html).

## Summary {#sec-summary}

### A minimalist and elegant presentation theme

The Quarto reveal.js clean theme aims to be a minimalist and elegant presention
theme. Here are some options to get you started:

Add the theme to an existing project.

```{.bash}
quarto install extension grantmcdermott/quarto-revealjs-clean
```

... or, create a new project using this slide deck as a lean template.

```{.bash}
quarto use template grantmcdermott/quarto-revealjs-clean
```

... or, create a new project using the demo slide deck as a full template.

```{.bash}
quarto use template grantmcdermott/quarto-revealjs-clean-demo
```
